mode: rule
log-level: info
dns:
  default-nameserver:
    - 114.114.115.115
    - 119.28.28.28
    - 223.6.6.6
    - system
  nameserver:
    - https://223.5.5.5/dns-query
    - https://223.6.6.6/dns-query
    - https://1.12.12.12/dns-query
    - https://120.53.53.53/dns-query
  fake-ip-filter:
    - '*'
    - +.lan
    - +.lical
script:
  shortcuts:
    quic: network == 'udp' and dst_port == 443
proxy-providers:
  WS:
    url: http://your-service-provider
    interval: 600
    benchmark-timeout: 5
    benchmark-url: http://www.gstatic.com/generate_204
  PY:
    interval: 86400
    url: http://your-service-provider
    benchmark-timeout: 5
    benchmark-url: http://www.gstatic.com/generate_204
  LH:
    benchmark-timeout: 5
    interval: 86400
    url: http://your-service-provider
    benchmark-url: http://www.gstatic.com/generate_204
proxy-groups:
  - name: PROXY
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/Proxy.png
    type: select
    proxies:
      - Automatic
      - Manual
      - æ¸¯æ¾³å°
      - Singapore
      - Japan
      - America
      - DIRECT
  - name: Final
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/Final.png
    type: select
    proxies:
      - PROXY
      - DIRECT
  - name: OpenAI
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/ChatGPT.png
    type: select
    proxies:
      - Automatic
      - Manual
      - æ¸¯æ¾³å°
      - Singapore
      - Japan
      - America
      - DIRECT
  - name: X
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/X.png
    type: select
    proxies:
      - Automatic
      - Manual
      - æ¸¯æ¾³å°
      - Singapore
      - Japan
      - America
      - DIRECT
  - name: Talkatone
    icon: https://raw.githubusercontent.com/qsoyq/icons/main/assets/icon/talkatone.png
    type: select
    proxies:
      - Automatic
      - Manual
      - æ¸¯æ¾³å°
      - Singapore
      - Japan
      - America
      - DIRECT
  - name: Telegram
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Telegram.png
    type: select
    proxies:
      - Automatic
      - Manual
      - æ¸¯æ¾³å°
      - Singapore
      - Japan
      - America
      - DIRECT
  - icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/TikTok.png
    name: Tiktok
    proxies:
      - Automatic
      - Manual
      - æ¸¯æ¾³å°
      - Singapore
      - Japan
      - America
      - DIRECT
    type: select
  - name: Apple
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Apple.png
    type: select
    proxies:
      - Automatic
      - Manual
      - æ¸¯æ¾³å°
      - Singapore
      - Japan
      - America
      - DIRECT
  - name: Google
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Google_Search.png
    type: select
    proxies:
      - Automatic
      - Manual
      - æ¸¯æ¾³å°
      - Singapore
      - Japan
      - America
      - DIRECT
  - name: YouTube
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/YouTube.png
    type: select
    proxies:
      - Automatic
      - Manual
      - æ¸¯æ¾³å°
      - Singapore
      - Japan
      - America
      - DIRECT
  - name: Automatic
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/Auto.png
    interval: 120
    lazy: true
    tolerance: 50
    type: url-test
    include-all: true
    hidden: null
    filter: ^(?!.*(?:å¥—é¤åˆ°æœŸ|å‰©ä½™æµé‡|å…³æ³¨|è®¢é˜…|åŠ å…¥|LanHai|Expire|cfnat|50 GB))
  - name: Manual
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/Static.png
    interval: 120
    lazy: true
    type: select
    include-all: true
    proxies: null
    filter: ^(?!.*(?:å¥—é¤åˆ°æœŸ|å‰©ä½™æµé‡|å…³æ³¨|è®¢é˜…|åŠ å…¥|LanHai|Expire|cfnat|50 GB))
  - name: æ¸¯æ¾³å°
    filter: "æ¾³é—¨|ğŸ‡²ğŸ‡´|æ¸¯|ğŸ‡­ğŸ‡°|HK|(?i)Hong| å°|ğŸ‡¹ğŸ‡¼|æ¹¾|TW|(?i)Taiwan"
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/China.png
    interval: 120
    lazy: true
    tolerance: 50
    type: select
    include-all: true
    proxies:
      - HK-Auto
      - HK-FallBack
      - HK-LoadBalance
  - name: Singapore
    filter: "æ–°åŠ å¡|å¡|ç‹®åŸ|ğŸ‡¸ğŸ‡¬|SG|(?i)Singapore"
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/Singapore.png
    interval: 120
    lazy: true
    tolerance: 50
    type: select
    include-all: true
    proxies:
      - SG-Auto
      - SG-FallBack
      - SG-LoadBalance
  - name: Japan
    filter: "æ—¥|ğŸ‡¯ğŸ‡µ|ä¸œäº¬|JP|(?i)Japan"
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/Japan.png
    interval: 120
    lazy: true
    tolerance: 50
    type: select
    include-all: true
    proxies:
      - JP-Auto
      - JP-FallBack
      - JP-LoadBalance
  - name: America
    filter: "ç¾|ğŸ‡ºğŸ‡²|US|(?i)States|America"
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/United_States.png
    interval: 120
    lazy: true
    tolerance: 50
    type: select
    include-all: true
    proxies:
      - US-Auto
      - US-FallBack
      - US-LoadBalance
  - name: Bilibili
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/bilibili_3.png
    type: select
    proxies:
      - Automatic
      - Manual
      - æ¸¯æ¾³å°
      - Singapore
      - Japan
      - America
      - DIRECT
  - name: Emby
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Emby.png
    type: select
    proxies:
      - Automatic
      - Manual
      - æ¸¯æ¾³å°
      - Singapore
      - Japan
      - America
      - DIRECT
  - name: NetEaseMusic
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Netease_Music.png
    type: select
    proxies:
      - Automatic
      - Manual
      - æ¸¯æ¾³å°
      - Singapore
      - Japan
      - America
      - DIRECT
  - name: Microsoft
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Windows_11.png
    type: select
    proxies:
      - Automatic
      - Manual
      - æ¸¯æ¾³å°
      - Singapore
      - Japan
      - America
      - DIRECT
  - name: Streaming
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Streaming.png
    type: select
    proxies:
      - Automatic
      - Manual
      - æ¸¯æ¾³å°
      - Singapore
      - Japan
      - America
      - DIRECT
  - name: Netflix
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/Netflix.png
    type: select
    proxies:
      - Automatic
      - Manual
      - æ¸¯æ¾³å°
      - Singapore
      - Japan
      - America
      - DIRECT
  - name: Disney+
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/Disney%2B.png
    type: select
    proxies:
      - Automatic
      - Manual
      - æ¸¯æ¾³å°
      - Singapore
      - Japan
      - America
      - DIRECT
  - name: Spotify
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/Spotify.png
    type: select
    proxies:
      - Automatic
      - Manual
      - æ¸¯æ¾³å°
      - Singapore
      - Japan
      - America
      - DIRECT
  - name: Games
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Game.png
    type: select
    proxies:
      - Automatic
      - Manual
      - æ¸¯æ¾³å°
      - Singapore
      - Japan
      - America
      - DIRECT
  - name: HK-Auto
    type: url-test
    hidden: true
    include-all: true
    filter: æ¾³é—¨|ğŸ‡²ğŸ‡´|æ¸¯|ğŸ‡­ğŸ‡°|HK|(?i)Hong
    interval: 300
    lazy: true
  - name: SG-Auto
    type: url-test
    hidden: true
    include-all: true
    filter: æ–°åŠ å¡|å¡|ç‹®åŸ|ğŸ‡¸ğŸ‡¬|SG|(?i)Singapore
    interval: 300
    lazy: true
  - name: JP-Auto
    type: url-test
    hidden: true
    include-all: true
    filter: æ—¥|ğŸ‡¯ğŸ‡µ|ä¸œäº¬|JP|(?i)Japan
    interval: 300
    lazy: true
  - name: US-Auto
    type: url-test
    hidden: true
    include-all: true
    filter: ç¾|ğŸ‡ºğŸ‡²|US|(?i)States|America
    interval: 300
    lazy: true
  - name: HK-FallBack
    type: fallback
    hidden: true
    include-all: true
    filter: æ¾³é—¨|ğŸ‡²ğŸ‡´|æ¸¯|ğŸ‡­ğŸ‡°|HK|(?i)Hong
    interval: 300
    lazy: true
  - name: SG-FallBack
    type: fallback
    hidden: true
    include-all: true
    filter: æ–°åŠ å¡|å¡|ç‹®åŸ|ğŸ‡¸ğŸ‡¬|SG|(?i)Singapore
    interval: 300
    lazy: true
  - name: JP-FallBack
    type: fallback
    hidden: true
    include-all: true
    filter: æ—¥|ğŸ‡¯ğŸ‡µ|ä¸œäº¬|JP|(?i)Japan
    interval: 300
    lazy: true
  - name: US-FallBack
    type: fallback
    hidden: true
    include-all: true
    filter: ç¾|ğŸ‡ºğŸ‡²|US|(?i)States|America
    interval: 300
    lazy: true
  - name: HK-LoadBalance
    type: load-balance
    hidden: true
    include-all: true
    filter: æ¾³é—¨|ğŸ‡²ğŸ‡´|æ¸¯|ğŸ‡­ğŸ‡°|HK|(?i)Hong
    strategy: consistent-hashing
    interval: 300
    lazy: true
  - name: SG-LoadBalance
    type: load-balance
    hidden: true
    include-all: true
    filter: æ–°åŠ å¡|å¡|ç‹®åŸ|ğŸ‡¸ğŸ‡¬|SG|(?i)Singapore
    strategy: consistent-hashing
    interval: 300
    lazy: true
  - name: JP-LoadBalance
    type: load-balance
    hidden: true
    include-all: true
    filter: æ—¥|ğŸ‡¯ğŸ‡µ|ä¸œäº¬|JP|(?i)Japan
    strategy: consistent-hashing
    interval: 300
    lazy: true
  - name: US-LoadBalance
    type: load-balance
    hidden: true
    include-all: true
    filter: ç¾|ğŸ‡ºğŸ‡²|US|(?i)States|America
    strategy: consistent-hashing
    interval: 300
    lazy: true
rules:
  - RULE-SET,AI,OpenAI
  - RULE-SET,Apple,Apple
  - RULE-SET,AppleProxyService,America
  - RULE-SET,Bahamut,æ¸¯æ¾³å°
  - RULE-SET,BiliIntl,Streaming
  - RULE-SET,Bilibili,Bilibili
  - RULE-SET,ChinaDomain,DIRECT
  - RULE-SET,ProxyMedia,Streaming
  - RULE-SET,ProxyGFW,PROXY
  - RULE-SET,WeChat,DIRECT
  - RULE-SET,Talkatone,Talkatone
  - RULE-SET,TalkatoneAD,REJECT
  - SCRIPT,quic,REJECT
  - RULE-SET,Netflix,Netflix
  - RULE-SET,Disney+,Disney+
  - RULE-SET,Spotify,Spotify
  - RULE-SET,GitHub,PROXY
  - RULE-SET,Telegram,Telegram
  - RULE-SET,YouTube,YouTube
  - RULE-SET,Google,Google
  - RULE-SET,Twitter,X
  - DOMAIN-SUFFIX,tapbots.com,PROXY
  - GEOSITE,instagram,PROXY
  - GEOSITE,facebook,PROXY
  # Steam
  - GEOSITE,steam@cn,DIRECT
  - GEOSITE,steam,PROXY
  - PROCESS-NAME,trustd,PROXY
  # Microsoft
  - GEOSITE,microsoft@cn,DIRECT
  - GEOSITE,microsoft,PROXY
  - GEOSITE,xbox,PROXY
  # common proxy utils
  - PROCESS-NAME,v2ray,DIRECT
  - PROCESS-NAME,Surge,DIRECT
  - PROCESS-NAME,ss-local,DIRECT
  - PROCESS-NAME,privoxy,DIRECT
  - PROCESS-NAME,trojan,DIRECT
  - PROCESS-NAME,trojan-go,DIRECT
  - PROCESS-NAME,naive,DIRECT
  - PROCESS-NAME,CloudflareWARP,DIRECT
  - PROCESS-NAME,Cloudflare WARP,DIRECT
  - IP-CIDR,162.159.193.0/24,DIRECT,no-resolve
  - PROCESS-NAME,p4pclient,DIRECT
  - PROCESS-NAME,Thunder,DIRECT
  - PROCESS-NAME,DownloadService,DIRECT
  - PROCESS-NAME,qbittorrent,DIRECT
  - PROCESS-NAME,Transmission,DIRECT
  - PROCESS-NAME,fdm,DIRECT
  - PROCESS-NAME,aria2c,DIRECT
  - PROCESS-NAME,Folx,DIRECT
  - PROCESS-NAME,NetTransport,DIRECT
  - PROCESS-NAME,uTorrent,DIRECT
  - PROCESS-NAME,WebTorrent,DIRECT
  - GEOIP,LAN,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,Final
rule-providers:
  AI:
    behavior: classical
    format: text
    interval: 86400
    url: https://raw.githubusercontent.com/jovinleung/Tool/main/Stash/Rules/AI.list
  YouTube:
    behavior: classical
    format: text
    interval: 86400
    url: https://raw.githubusercontent.com/jovinleung/Tool/main/Stash/Rules/YouTube.list
  Netflix:
    behavior: classical
    format: text
    interval: 86400
    url: https://raw.githubusercontent.com/jovinleung/Tool/main/Stash/Rules/Netflix.list
  Disney+:
    behavior: classical
    format: text
    interval: 86400
    url: https://raw.githubusercontent.com/jovinleung/Tool/main/Stash/Rules/Disney.list
  Emby:
    behavior: classical
    format: text
    interval: 86400
    url: https://raw.githubusercontent.com/jovinleung/Tool/main/Stash/Rules/Emby.list
  TikTok:
    behavior: classical
    format: text
    interval: 86400
    url: https://raw.githubusercontent.com/jovinleung/Tool/main/Stash/Rules/TikTok.list
  Bahamut:
    behavior: classical
    format: text
    interval: 86400
    url: https://raw.githubusercontent.com/jovinleung/Tool/main/Stash/Rules/Bahamut.list
  BiliIntl:
    behavior: classical
    format: text
    interval: 86400
    url: https://raw.githubusercontent.com/jovinleung/Tool/main/Stash/Rules/BiliBiliIntl.list
  Bilibili:
    behavior: classical
    format: text
    interval: 86400
    url: https://raw.githubusercontent.com/jovinleung/Tool/main/Stash/Rules/Bilibili.list
  Spotify:
    behavior: classical
    format: text
    interval: 86400
    url: https://raw.githubusercontent.com/jovinleung/Tool/main/Stash/Rules/Spotify.list
  NetEaseMusic:
    behavior: classical
    format: text
    interval: 86400
    url: https://raw.githubusercontent.com/jovinleung/Tool/main/Stash/Rules/NetEaseMusic.list
  ProxyMedia:
    behavior: classical
    format: text
    interval: 86400
    url: https://raw.githubusercontent.com/jovinleung/Tool/main/Stash/Rules/ProxyMedia.list
  WeChat:
    behavior: classical
    format: text
    interval: 86400
    url: https://raw.githubusercontent.com/jovinleung/Tool/main/Stash/Rules/WeChat.list
  Talkatone:
    behavior: classical
    format: text
    interval: 86400
    url: https://raw.githubusercontent.com/jovinleung/Tool/main/Stash/Rules/Talkatone.list
  Telegram:
    behavior: classical
    format: text
    interval: 86400
    url: https://raw.githubusercontent.com/jovinleung/Tool/main/Stash/Rules/Telegram.list
  GitHub:
    behavior: classical
    format: text
    interval: 86400
    url: https://raw.githubusercontent.com/jovinleung/Tool/main/Stash/Rules/Github.list
  Twitter:
    behavior: classical
    format: text
    interval: 86400
    url: https://raw.githubusercontent.com/jovinleung/Tool/main/Stash/Rules/Twitter.list
  AppleProxyService:
    behavior: classical
    format: text
    interval: 86400
    url: https://raw.githubusercontent.com/jovinleung/Tool/main/Stash/Rules/AppleProxyService.list
  Apple:
    behavior: classical
    format: text
    interval: 86400
    url: https://raw.githubusercontent.com/jovinleung/Tool/main/Stash/Rules/Apple.list
  Google:
    behavior: classical
    format: text
    interval: 86400
    url: https://raw.githubusercontent.com/jovinleung/Tool/main/Stash/Rules/Google.list
  Microsoft:
    behavior: classical
    format: text
    interval: 86400
    url: https://raw.githubusercontent.com/jovinleung/Tool/main/Stash/Rules/Microsoft.list
  Games:
    behavior: classical
    format: text
    interval: 86400
    url: https://raw.githubusercontent.com/jovinleung/Tool/main/Stash/Rules/Game.list
  ChinaDomain:
    behavior: classical
    format: text
    interval: 86400
    url: https://raw.githubusercontent.com/jovinleung/Tool/main/Stash/Rules/ChinaDomain.list
  ProxyGFW:
    behavior: classical
    format: text
    interval: 86400
    url: https://raw.githubusercontent.com/jovinleung/Tool/main/Stash/Rules/ProxyGFW.list
  TalkatoneAD:
    behavior: classical
    format: text
    interval: 86400
    url: https://raw.githubusercontent.com/jovinleung/Tool/main/Stash/Rules/TalkatoneAD.list
